[workspace]
resolver = "3"
members = [
    "compiler/sw_common",
    "compiler/sw_frontend",
    "compiler/sw_semantic",
    "compiler/sw_codegen_cranelift",
    "compiler/swc",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
publish = false

[workspace.dependencies]
sw-common = { path = "compiler/sw_common" }
sw-frontend = { path = "compiler/sw_frontend" }
sw-semantic = { path = "compiler/sw_semantic" }
sw-codegen-cranelift = { path = "compiler/sw_codegen_cranelift" }
