use sw_common::Span;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum IntegerSuffix {
    I8,
    I16,
    I32,
    I64,
    Isize,
    U8,
    U16,
    U32,
    U64,
    Usize,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum FloatSuffix {
    F32,
    F64,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Keyword {
    Async,
    Await,
    Break,
    Case,
    Catch,
    Class,
    Const,
    Constructor,
    Continue,
    Default,
    Defer,
    Destructor,
    Else,
    Enum,
    Export,
    Extends,
    False,
    Final,
    Finally,
    For,
    Function,
    If,
    Implements,
    Import,
    Interface,
    Internal,
    Let,
    New,
    Null,
    Of,
    Override,
    Private,
    Property,
    Protected,
    Public,
    Return,
    Static,
    Struct,
    Super,
    Switch,
    This,
    Throw,
    True,
    Try,
    Type,
    Using,
    Virtual,
    While,
    // 保留的“不支持”关键字：解析器给出明确错误。
    UnsupportedVar,
    UnsupportedUndefined,
    UnsupportedTypeof,
    UnsupportedInstanceof,
    UnsupportedDo,
}

impl Keyword {
    pub fn from_str(text: &str) -> Option<Keyword> {
        Some(match text {
            "async" => Keyword::Async,
            "await" => Keyword::Await,
            "break" => Keyword::Break,
            "case" => Keyword::Case,
            "catch" => Keyword::Catch,
            "class" => Keyword::Class,
            "const" => Keyword::Const,
            "constructor" => Keyword::Constructor,
            "continue" => Keyword::Continue,
            "default" => Keyword::Default,
            "defer" => Keyword::Defer,
            "destructor" => Keyword::Destructor,
            "else" => Keyword::Else,
            "enum" => Keyword::Enum,
            "export" => Keyword::Export,
            "extends" => Keyword::Extends,
            "false" => Keyword::False,
            "final" => Keyword::Final,
            "finally" => Keyword::Finally,
            "for" => Keyword::For,
            "function" => Keyword::Function,
            "if" => Keyword::If,
            "implements" => Keyword::Implements,
            "import" => Keyword::Import,
            "interface" => Keyword::Interface,
            "internal" => Keyword::Internal,
            "let" => Keyword::Let,
            "new" => Keyword::New,
            "null" => Keyword::Null,
            "of" => Keyword::Of,
            "override" => Keyword::Override,
            "private" => Keyword::Private,
            "property" => Keyword::Property,
            "protected" => Keyword::Protected,
            "public" => Keyword::Public,
            "return" => Keyword::Return,
            "static" => Keyword::Static,
            "struct" => Keyword::Struct,
            "super" => Keyword::Super,
            "switch" => Keyword::Switch,
            "this" => Keyword::This,
            "throw" => Keyword::Throw,
            "true" => Keyword::True,
            "try" => Keyword::Try,
            "type" => Keyword::Type,
            "using" => Keyword::Using,
            "virtual" => Keyword::Virtual,
            "while" => Keyword::While,
            "var" => Keyword::UnsupportedVar,
            "undefined" => Keyword::UnsupportedUndefined,
            "typeof" => Keyword::UnsupportedTypeof,
            "instanceof" => Keyword::UnsupportedInstanceof,
            "do" => Keyword::UnsupportedDo,
            _ => return None,
        })
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Keyword::Async => "async",
            Keyword::Await => "await",
            Keyword::Break => "break",
            Keyword::Case => "case",
            Keyword::Catch => "catch",
            Keyword::Class => "class",
            Keyword::Const => "const",
            Keyword::Constructor => "constructor",
            Keyword::Continue => "continue",
            Keyword::Default => "default",
            Keyword::Defer => "defer",
            Keyword::Destructor => "destructor",
            Keyword::Else => "else",
            Keyword::Enum => "enum",
            Keyword::Export => "export",
            Keyword::Extends => "extends",
            Keyword::False => "false",
            Keyword::Final => "final",
            Keyword::Finally => "finally",
            Keyword::For => "for",
            Keyword::Function => "function",
            Keyword::If => "if",
            Keyword::Implements => "implements",
            Keyword::Import => "import",
            Keyword::Interface => "interface",
            Keyword::Internal => "internal",
            Keyword::Let => "let",
            Keyword::New => "new",
            Keyword::Null => "null",
            Keyword::Of => "of",
            Keyword::Override => "override",
            Keyword::Private => "private",
            Keyword::Property => "property",
            Keyword::Protected => "protected",
            Keyword::Public => "public",
            Keyword::Return => "return",
            Keyword::Static => "static",
            Keyword::Struct => "struct",
            Keyword::Super => "super",
            Keyword::Switch => "switch",
            Keyword::This => "this",
            Keyword::Throw => "throw",
            Keyword::True => "true",
            Keyword::Try => "try",
            Keyword::Type => "type",
            Keyword::Using => "using",
            Keyword::Virtual => "virtual",
            Keyword::While => "while",
            Keyword::UnsupportedVar => "var",
            Keyword::UnsupportedUndefined => "undefined",
            Keyword::UnsupportedTypeof => "typeof",
            Keyword::UnsupportedInstanceof => "instanceof",
            Keyword::UnsupportedDo => "do",
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum TokenKind {
    Ident(String),
    Keyword(Keyword),
    Integer {
        text: String,
        suffix: Option<IntegerSuffix>,
    },
    Float {
        text: String,
        suffix: Option<FloatSuffix>,
    },
    Str(String),
    Char(char),
    TemplateStart,
    TemplateText(String),
    TemplateExprStart,
    TemplateEnd,
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Comma,
    Semicolon,
    Colon,
    Dot,
    At,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    StarStar,
    PlusPlus,
    MinusMinus,
    Assign,
    PlusAssign,
    MinusAssign,
    StarAssign,
    SlashAssign,
    PercentAssign,
    AmpAssign,
    PipeAssign,
    CaretAssign,
    ShlAssign,
    ShrAssign,
    CoalesceAssign,
    Eq,
    Ne,
    Lt,
    Le,
    Gt,
    Ge,
    AmpAmp,
    PipePipe,
    Bang,
    Amp,
    Pipe,
    Caret,
    Tilde,
    Shl,
    Shr,
    Question,
    QuestionQuestion,
    QuestionDot,
    FatArrow,
    DotDotDot,
    Eof,
}

#[derive(Clone, Debug)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}

impl Token {
    pub fn eof(at: usize) -> Token {
        Token {
            kind: TokenKind::Eof,
            span: Span::empty(at),
        }
    }

    pub fn is_keyword(&self, keyword: Keyword) -> bool {
        matches!(&self.kind, TokenKind::Keyword(found) if *found == keyword)
    }

    pub fn is_ident(&self, name: &str) -> bool {
        matches!(&self.kind, TokenKind::Ident(found) if found == name)
    }

    /// 供错误信息使用的简短描述。
    pub fn describe(&self) -> String {
        match &self.kind {
            TokenKind::Ident(name) => format!("标识符 `{name}`"),
            TokenKind::Keyword(keyword) => format!("关键字 `{}`", keyword.as_str()),
            TokenKind::Integer { text, .. } => format!("整数 `{text}`"),
            TokenKind::Float { text, .. } => format!("浮点数 `{text}`"),
            TokenKind::Str(_) => "字符串".to_owned(),
            TokenKind::Char(character) => format!("字符 `{character}`"),
            TokenKind::TemplateStart => "模板字符串".to_owned(),
            TokenKind::TemplateText(_) => "模板文本".to_owned(),
            TokenKind::TemplateExprStart => "${".to_owned(),
            TokenKind::TemplateEnd => "模板结束".to_owned(),
            TokenKind::LParen => "`(`".to_owned(),
            TokenKind::RParen => "`)`".to_owned(),
            TokenKind::LBrace => "`{`".to_owned(),
            TokenKind::RBrace => "`}`".to_owned(),
            TokenKind::LBracket => "`[`".to_owned(),
            TokenKind::RBracket => "`]`".to_owned(),
            TokenKind::Comma => "`,`".to_owned(),
            TokenKind::Semicolon => "`;`".to_owned(),
            TokenKind::Colon => "`:`".to_owned(),
            TokenKind::Dot => "`.`".to_owned(),
            TokenKind::At => "`@`".to_owned(),
            TokenKind::Plus => "`+`".to_owned(),
            TokenKind::Minus => "`-`".to_owned(),
            TokenKind::Star => "`*`".to_owned(),
            TokenKind::Slash => "`/`".to_owned(),
            TokenKind::Percent => "`%`".to_owned(),
            TokenKind::StarStar => "`**`".to_owned(),
            TokenKind::PlusPlus => "`++`".to_owned(),
            TokenKind::MinusMinus => "`--`".to_owned(),
            TokenKind::Assign => "`=`".to_owned(),
            TokenKind::PlusAssign => "`+=`".to_owned(),
            TokenKind::MinusAssign => "`-=`".to_owned(),
            TokenKind::StarAssign => "`*=`".to_owned(),
            TokenKind::SlashAssign => "`/=`".to_owned(),
            TokenKind::PercentAssign => "`%=`".to_owned(),
            TokenKind::AmpAssign => "`&=`".to_owned(),
            TokenKind::PipeAssign => "`|=`".to_owned(),
            TokenKind::CaretAssign => "`^=`".to_owned(),
            TokenKind::ShlAssign => "`<<=`".to_owned(),
            TokenKind::ShrAssign => "`>>=`".to_owned(),
            TokenKind::CoalesceAssign => "`??=`".to_owned(),
            TokenKind::Eq => "`==`".to_owned(),
            TokenKind::Ne => "`!=`".to_owned(),
            TokenKind::Lt => "`<`".to_owned(),
            TokenKind::Le => "`<=`".to_owned(),
            TokenKind::Gt => "`>`".to_owned(),
            TokenKind::Ge => "`>=`".to_owned(),
            TokenKind::AmpAmp => "`&&`".to_owned(),
            TokenKind::PipePipe => "`||`".to_owned(),
            TokenKind::Bang => "`!`".to_owned(),
            TokenKind::Amp => "`&`".to_owned(),
            TokenKind::Pipe => "`|`".to_owned(),
            TokenKind::Caret => "`^`".to_owned(),
            TokenKind::Tilde => "`~`".to_owned(),
            TokenKind::Shl => "`<<`".to_owned(),
            TokenKind::Shr => "`>>`".to_owned(),
            TokenKind::Question => "`?`".to_owned(),
            TokenKind::QuestionQuestion => "`??`".to_owned(),
            TokenKind::QuestionDot => "`?.`".to_owned(),
            TokenKind::FatArrow => "`=>`".to_owned(),
            TokenKind::DotDotDot => "`...`".to_owned(),
            TokenKind::Eof => "文件结束".to_owned(),
        }
    }
}
